# Generated by Django 3.2.6 on 2021-10-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
